name: CI

on:
    push:
        branches:
            - development
    pull_request:
        branches:
            - development

concurrency:
    group: ci-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    format:
        name: Prettier
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: 1.1.34
            - uses: actions/cache@v4
              with:
                  path: ~/.bun/install/cache
                  key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
                  restore-keys: |
                      ${{ runner.os }}-bun-
            - run: bun install --frozen-lockfile
            - run: bunx prettier --check .

    lint:
        name: ESLint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: 1.1.34
            - uses: actions/cache@v4
              with:
                  path: ~/.bun/install/cache
                  key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
                  restore-keys: |
                      ${{ runner.os }}-bun-
            - run: bun install --frozen-lockfile
            - run: bun run eslint .

    types:
        name: Type Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: 1.1.34
            - uses: actions/cache@v4
              with:
                  path: ~/.bun/install/cache
                  key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
                  restore-keys: |
                      ${{ runner.os }}-bun-
            - run: bun install --frozen-lockfile
            - run: bun run check-types

    build:
        name: Build
        runs-on: ubuntu-latest
        needs: [format, lint, types]
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: 1.1.34
            - uses: actions/cache@v4
              with:
                  path: ~/.bun/install/cache
                  key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}

                  restore-keys: |
                      ${{ runner.os }}-bun-
            - run: bun install --frozen-lockfile
            - run: bun run build
